/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.epseelon.todolist.dto {

[Bindable]
[RemoteClass(alias="org.epseelon.todolist.dto.TodoListItem")]
public class TodoListItem extends TodoListItemBase {
    public function TodoListItem() {
        super();
    }

}
}