/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.epseelon.todolist.dto {

[Bindable]
[RemoteClass(alias="org.epseelon.todolist.dto.TodoDetail")]
public class TodoDetail extends TodoDetailBase {
    public function TodoDetail(source:TodoDetail = null) {
        super();
        this.id = -1;
        if (source != null) {
            this.id = source.id;
            this.title = source.title;
            this.priority = source.priority;
            this.description = source.description;
        }
    }

}
}