/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.epseelon.todolist.dto {

[Bindable]
[RemoteClass(alias="org.epseelon.todolist.dto.TodoListDetail")]
public class TodoListDetail extends TodoListDetailBase {
    public function TodoListDetail(source:TodoListDetail = null) {
        super();
        this.id = -1;
        if (source != null) {
            this.id = source.id;
            this.name = source.name;
            for each(var todo:TodoDetail in source.todos) {
                this.todos.addItem(new TodoDetail(todo));
            }
        }
    }

}
}