/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED CLASS (TodoListItem.as).
 */

package org.epseelon.todolist.dto {

import flash.events.EventDispatcher;
import flash.utils.IDataInput;
import flash.utils.IDataOutput;

import mx.events.PropertyChangeEvent;

[Bindable]
[Event(name="propertyChange",type="mx.events.PropertyChangeEvent")]
public class TodoListItemBase extends EventDispatcher {

    private var _id:Number;
    private var _name:String;

    public function TodoListItemBase() {

    }


    public function set id(value:Number):void {
        if (_id != value) {
            var oldValue:Number = _id;
            _id = value;
            dispatchEvent(PropertyChangeEvent.createUpdateEvent(this, "id", oldValue, value));
        }
    }

    public function get id():Number {
        return _id;
    }

    public function set name(value:String):void {
        if (_name != value) {
            var oldValue:String = _name;
            _name = value;
            dispatchEvent(PropertyChangeEvent.createUpdateEvent(this, "name", oldValue, value));
        }
    }

    public function get name():String {
        return _name;
    }

    override public function addEventListener(type:String, listener:Function, useCapture:Boolean = false, priority:int = 0, useWeakReference:Boolean = false):void {
        super.addEventListener(type, listener, useCapture, priority, useWeakReference);

    }


    public function readExternal(input:IDataInput):void {
        _id = function(o:*):Number {
            return (o is Number ? o as Number : Number.NaN);
        }(input.readObject());
        _name = input.readObject() as String;
    }

    public function writeExternal(output:IDataOutput):void {
        output.writeObject(_id);
        output.writeObject(_name);
    }
}
}