/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package org.epseelon.todolist.enums {

import org.granite.util.Enum;

[Bindable]
[RemoteClass(alias="org.epseelon.todolist.enums.Priority")]
public class Priority extends Enum {

    public static const HIGH:Priority = new Priority("HIGH", _);
    public static const MEDIUM:Priority = new Priority("MEDIUM", _);
    public static const LOW:Priority = new Priority("LOW", _);

    function Priority(value:String = null, restrictor:* = null) {
        super((value || HIGH.name), restrictor);
    }

    override protected function getConstants():Array {
        return constants;
    }

    public static function get constants():Array {
        return [HIGH, MEDIUM, LOW];
    }

    public static function valueOf(name:String):Priority {
        return Priority(HIGH.constantOf(name));
    }
}
}